# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-gusto` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-gusto`.


# This cop enforces that polymorphic relations have a corresponding validation
# for their type field with an inclusion validation. This is required in order for Tapioca
# to generate correct Sorbet types
#
# pkg:gem/rubocop-gusto#lib/rubocop/gusto/version.rb:3
module RuboCop; end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:5
module RuboCop::Cop::Gusto; end

# Do not use Bootsnap to load files. Use `require` instead.
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:7
class RuboCop::Cop::Gusto::BootsnapLoadFile < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:15
  def file_read(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:18
  def load_inside_file_open(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:31
  def on_block(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:36
  def on_itblock(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:37
  def on_numblock(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:39
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:12
  def yaml_or_json_load(param0 = T.unsafe(nil)); end

  private

  # Look for File.read as the first argument
  #
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:48
  def on_load(node, constant_node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:8
RuboCop::Cop::Gusto::BootsnapLoadFile::PROHIBITED_CONSTANTS = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/bootsnap_load_file.rb:9
RuboCop::Cop::Gusto::BootsnapLoadFile::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/datadog_constant.rb:6
class RuboCop::Cop::Gusto::DatadogConstant < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/datadog_constant.rb:10
  def on_const(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/datadog_constant.rb:7
RuboCop::Cop::Gusto::DatadogConstant::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/datadog_constant.rb:8
RuboCop::Cop::Gusto::DatadogConstant::NAMESPACE = T.let(T.unsafe(nil), String)

# Flags installation of discouraged gems (e.g., timecop) in Gemfiles and gemspecs.
#
# Configuration:
#   Gems:
#     timecop: "Use Rails' time helpers (e.g., freeze_time, travel_to) instead of Timecop."
#
# This cop is intended to be enabled in Rails projects via config/rails.yml.
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:13
class RuboCop::Cop::Gusto::DiscouragedGem < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:18
  def on_send(node); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:40
  def advice_for(gem); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:24
  def check_gem_usage(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:32
  def discouraged_gems; end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:44
  def gems_config; end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:36
  def message_for(gem); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:14
RuboCop::Cop::Gusto::DiscouragedGem::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/discouraged_gem.rb:16
RuboCop::Cop::Gusto::DiscouragedGem::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/execute_migration.rb:6
class RuboCop::Cop::Gusto::ExecuteMigration < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/execute_migration.rb:10
  def on_send(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/execute_migration.rb:7
RuboCop::Cop::Gusto::ExecuteMigration::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/execute_migration.rb:8
RuboCop::Cop::Gusto::ExecuteMigration::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/factory_classes_or_modules.rb:6
class RuboCop::Cop::Gusto::FactoryClassesOrModules < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/factory_classes_or_modules.rb:9
  def on_class(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/factory_classes_or_modules.rb:13
  def on_module(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/factory_classes_or_modules.rb:7
RuboCop::Cop::Gusto::FactoryClassesOrModules::MSG = T.let(T.unsafe(nil), String)

# Checks for the use of `min` or `max` with a proc. Corrects to `min_by` or `max_by`.
#
# @safety This cop is unsafe because it will change the behavior of the code.
#
# @example
#  # bad
#  arr = [[3, 3, 3], [2, 2], [1]]
#  arr.min(&:count)
#   => [3, 3, 3] - oh no how did this happen?
#  arr = [[2,2],[1,1],[3,3,3]]
#  arr.min &:first # => TypeError: no implicit conversion of Array into Integer
#  arr = [[1, 1], [3, 3], [2, 2]]
#  arr.max { |pair| pair.first } # => [2, 2] (semantically incorrect)
#
#  # good
#  arr = [[2,2],[1],[3,3,3]]
#  arr.min_by &:first # => [1]
#  arr = [[1, 1], [3, 3], [2, 2]]
#  arr.max_by { |pair| pair.first } # => [3, 3]
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/min_by_max_by.rb:26
class RuboCop::Cop::Gusto::MinByMaxBy < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/min_by_max_by.rb:41
  def on_csend(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/min_by_max_by.rb:32
  def on_send(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/min_by_max_by.rb:29
RuboCop::Cop::Gusto::MinByMaxBy::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/min_by_max_by.rb:30
RuboCop::Cop::Gusto::MinByMaxBy::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Checks and discourages the use of metaprogramming techniques that make code harder to
# understand, debug, and maintain.
#
# @example
#
#   # bad - using define_method
#   define_method(:my_method) do |arg|
#     puts arg
#   end
#
#   # good - using regular method definition
#   def my_method(arg)
#     puts arg
#   end
#
#   # bad - using instance_eval
#   object.instance_eval do
#     def foo
#       bar
#     end
#   end
#
#   # good - defining methods on the class
#   class MyClass
#     def foo
#       bar
#     end
#   end
#
#   # bad - using method_missing
#   def method_missing(method, *args)
#     if method.to_s.start_with?('find_by_')
#       # ...
#     end
#   end
#
#   # bad - using define_singleton_method
#   object.define_singleton_method(:foo) { bar }
#
#   # good - define class methods directly
#   def self.foo
#     bar
#   end
#
#   # bad - using class_eval
#   MyClass.class_eval do
#     def foo
#       bar
#     end
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:57
class RuboCop::Cop::Gusto::NoMetaprogramming < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:61
  def included_definition?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:66
  def inherited_definition?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:105
  def on_def(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:95
  def on_defs(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:111
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:86
  def using_class_eval?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:76
  def using_define_method?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:91
  def using_define_singleton_method_on_klass_instance?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:81
  def using_instance_eval?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:71
  def using_method_missing?(param0 = T.unsafe(nil)); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_metaprogramming.rb:58
RuboCop::Cop::Gusto::NoMetaprogramming::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Checks for the presence of error message checking within rescue blocks.
#
# This is brittle and can break easily.
#
# NOTE: We submitted this upstream here: https://github.com/rubocop/rubocop/pull/13352
#
# @example
#
#   # bad
#   begin
#     something
#   rescue => e
#     if e.message.match?(/Duplicate entry/)
#       handle_error
#     end
#   end
#
#  # bad
#  begin
#    something
#  rescue => e
#    unless e.message.match?(/Duplicate entry/)
#      handle_error
#    end
#  end
#
#   # good
#   begin
#     something
#   rescue ActiveRecord::RecordNotUnique => e
#     handle_error
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_rescue_error_message_checking.rb:39
class RuboCop::Cop::Gusto::NoRescueErrorMessageChecking < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_rescue_error_message_checking.rb:43
  def on_rescue(node); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_rescue_error_message_checking.rb:51
  def message_check?(condition_node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_rescue_error_message_checking.rb:41
RuboCop::Cop::Gusto::NoRescueErrorMessageChecking::METHODS_TO_CHECK = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_rescue_error_message_checking.rb:40
RuboCop::Cop::Gusto::NoRescueErrorMessageChecking::MSG = T.let(T.unsafe(nil), String)

# Do not call a private method via __send__
#
# @example
#   # bad
#   foo.__send__(:bar)
#   __send__(:run_baz)
#
#   # good
#   There's no better alternative, don't call private methods.
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:16
class RuboCop::Cop::Gusto::NoSend < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:21
  def invoke_private_method_send?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:28
  def on_csend(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:25
  def on_send(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:17
RuboCop::Cop::Gusto::NoSend::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/no_send.rb:18
RuboCop::Cop::Gusto::NoSend::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/paperclip_or_attachable.rb:7
class RuboCop::Cop::Gusto::PaperclipOrAttachable < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/paperclip_or_attachable.rb:11
  def on_send(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/paperclip_or_attachable.rb:8
RuboCop::Cop::Gusto::PaperclipOrAttachable::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/paperclip_or_attachable.rb:9
RuboCop::Cop::Gusto::PaperclipOrAttachable::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Checks for a defined `.perform` class method in Sidekiq workers. These
# are most likely intended to have been instance methods.
#
# @example
#   # bad
#   class MyWorker
#     include Sidekiq::Worker
#
#     def self.perform
#       # ...
#     end
#   end
#
#   # good
#   class MyWorker
#     include Sidekiq::Worker
#
#     def perform
#       # ...
#     end
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:28
class RuboCop::Cop::Gusto::PerformClassMethod < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:38
  def on_def(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:45
  def on_defs(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:34
  def worker_module_include?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:57
  def is_sidekiq_worker?(search_node, method_type); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:49
  def perform_class_method_type(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:65
  def worker_modules; end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:29
RuboCop::Cop::Gusto::PerformClassMethod::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:30
RuboCop::Cop::Gusto::PerformClassMethod::WORKER_FALLBACK = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/perform_class_method.rb:31
RuboCop::Cop::Gusto::PerformClassMethod::WORKER_MODULES = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:9
class RuboCop::Cop::Gusto::PolymorphicTypeValidation < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:54
  def allow_blank?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:44
  def inclusion_in?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:58
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:49
  def polymorphic_methods_for?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:34
  def polymorphic_relation?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:39
  def type_validation?(param0 = T.unsafe(nil)); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:31
RuboCop::Cop::Gusto::PolymorphicTypeValidation::ALLOW_BLANK_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:12
RuboCop::Cop::Gusto::PolymorphicTypeValidation::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/polymorphic_type_validation.rb:10
RuboCop::Cop::Gusto::PolymorphicTypeValidation::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Don't use the `$?` or `$CHILD_STATUS` global variables. Instead, use `Process.last_status`
#
# @example
#   # bad
#   $?.exitstatus
#   $CHILD_STATUS.success?
#
#   # good
#   Process.last_status.exit_status
#   Process.last_status.success?
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/prefer_process_last_status.rb:17
class RuboCop::Cop::Gusto::PreferProcessLastStatus < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/prefer_process_last_status.rb:29
  def autocorrect(corrector, node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/prefer_process_last_status.rb:23
  def on_gvar(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/prefer_process_last_status.rb:20
RuboCop::Cop::Gusto::PreferProcessLastStatus::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/prefer_process_last_status.rb:21
RuboCop::Cop::Gusto::PreferProcessLastStatus::OFFENDERS = T.let(T.unsafe(nil), Set)

# Disallows the use of `extends` in Rabl templates due to poor caching performance.
# Inline the templating to generate your JSON instead.
#
# @example
#   # bad
#   extends 'path/to/template'
#
#   # bad - but not covered by this rule
#   partial 'path/to/template'
#
#   # good - inline your templating
#   node 'some_node'
#   attributes :foo, :bar
#   child(:baz) { attributes :qux }
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:21
class RuboCop::Cop::Gusto::RablExtends < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:31
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:27
  def rabl_extends?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:37
  def relevant_file?(file); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:22
RuboCop::Cop::Gusto::RablExtends::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:23
RuboCop::Cop::Gusto::RablExtends::RABL_EXTENSION = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rabl_extends.rb:24
RuboCop::Cop::Gusto::RablExtends::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# NOTE: Being pushed upstream here: https://github.com/rubocop/rubocop-rails/pull/1375
# Checks for usage of `Rails.env` which can be replaced with Feature Flags
#
# Although `local?` is a form of an environment-specific check, it is allowed because
# it cannot be used to control overall environment rollout, but it can be helpful to
# distinguish or protect code that is explicitly written to only ever execute in a
# dev or test environment. `local?` is also a form of a feature flag.
#
# @example
#
#   # bad
#   Rails.env.production? || Rails.env.demo?
#
#   # good
#   if FeatureFlag.enabled?(:new_feature)
#     # new feature code
#   end
#
#   # good
#   raise unless Rails.env.local?
#
#   # good
#   abort ("The Rails environment is running in production mode!") unless Rails.env.local?
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:30
class RuboCop::Cop::Gusto::RailsEnv < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:65
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:58
  def prohibited_rails_env?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:71
  def prohibited_predicate?(name); end
end

# This allow list is derived from:
# (Rails.env.methods - Object.instance_methods).select { |m| m.to_s.end_with?('?') }
# and then removing the environment specific methods like development?, test?, production?
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:34
RuboCop::Cop::Gusto::RailsEnv::ALLOWED_LIST = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:54
RuboCop::Cop::Gusto::RailsEnv::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rails_env.rb:55
RuboCop::Cop::Gusto::RailsEnv::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Detects constants in a rake file because they are defined at the top level.
# It is confusing because the scope looks like it would be in the task or namespace,
# but actually it is defined at the top level.
#
# @example
#   # bad
#   task :foo do
#     class C
#     end
#   end
#
#   # bad
#   namespace :foo do
#     module M
#     end
#   end
#
#   # good - It is also defined at the top level,
#   #        but it looks like intended behavior.
#   class C
#   end
#   task :foo do
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:30
class RuboCop::Cop::Gusto::RakeConstants < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:42
  def on_casgn(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:48
  def on_class(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:54
  def on_module(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:34
  def task_or_namespace?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:62
  def in_task_or_namespace?(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rake_constants.rb:31
RuboCop::Cop::Gusto::RakeConstants::MSG = T.let(T.unsafe(nil), String)

# Ensures that regular expressions use `\A` and `\z` anchors instead
# of `^` and `$` when matching the start or end of a string. This is
# critical for security validations as `^` and `$` will match the start/end
# of any line in a string, not just the start/end of the entire string.
#
# @example
#   # bad - validating only a single line of input which could be split across multiple lines
#   /^foo/
#   /foo$/
#   /^foo$/
#
#   # good
#   /\Afoo/
#   /foo\z/
#   /\Afoo\z/
#
#   # good - multiline mode is allowed
#   /^foo/m
#   /foo$/m
#
#   # okay - anchors in the middle of the pattern are not flagged
#   /foo^bar/
#   /foo$bar/
#
# @safety
#   We choose to consider this cop safe even though the code is not equivalent.
#   Replacing `^` and `$` with `\A` and `\z` will make the regex more strict,
#   which is the intended behavior for securely validating input.
#
# @see https://ruby-doc.org/core/Regexp.html
# @see https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/regexp_bypass.rb:38
class RuboCop::Cop::Gusto::RegexpBypass < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/regexp_bypass.rb:45
  def on_regexp(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/regexp_bypass.rb:41
RuboCop::Cop::Gusto::RegexpBypass::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/regexp_bypass.rb:42
RuboCop::Cop::Gusto::RegexpBypass::PROHIBITED_ANCHOR = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/regexp_bypass.rb:43
RuboCop::Cop::Gusto::RegexpBypass::PROHIBITED_END_ANCHOR = T.let(T.unsafe(nil), String)

# Never mock time in specs. Use Rails Testing Time Helpers (eg `freeze_time` and `travel_to`) instead.
# .and_call_original is allowed.
#
# @example
#   # bad
#   context 'time specific tests' do
#     before { allow(Time).to receive(:now).and_return(current_time) }
#     it 'does stuff in a fixed time' do
#       subject
#     end
#   end
#
#   # good
#   context 'time specific tests' do
#     it 'does stuff in a fixed time' do
#       freeze_time do
#         subject
#       end
#     end
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:27
class RuboCop::Cop::Gusto::RspecDateTimeMock < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:37
  def and_call_original?(param0); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:59
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:48
  def time_mock?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:92
  def and_call_original_in_chain?(node); end

  # Returns true if the given node is a const or a call chain whose root receiver
  # is one of the protected time classes (Date/Time/DateTime)
  #
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:74
  def rooted_in_time_class?(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:28
RuboCop::Cop::Gusto::RspecDateTimeMock::CLASSES = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:33
RuboCop::Cop::Gusto::RspecDateTimeMock::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/rspec_date_time_mock.rb:34
RuboCop::Cop::Gusto::RspecDateTimeMock::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/sidekiq_params.rb:6
class RuboCop::Cop::Gusto::SidekiqParams < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/sidekiq_params.rb:14
  def on_def(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/sidekiq_params.rb:10
  def perform_with_kwargs?(param0 = T.unsafe(nil)); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/sidekiq_params.rb:7
RuboCop::Cop::Gusto::SidekiqParams::MSG = T.let(T.unsafe(nil), String)

# Checks that no top-level constants (excluding classes and modules)
# are defined. This rule exists to prevent accidental pollution of the
# global namespace as well as cases where application code has
# accidentally depended on test code.
#
# By default, this check is limited to files in `app/`, `lib/`, and
# `spec/` directories, except in the root of `lib/` and in support files
# in `spec/support/`.
#
# @example when in a checked directory
#   # bad
#   FOO = 'bar' # lib/foo/bar.rb
#
#   # bad
#   FOO = 'bar' # app/models/foo.rb
#
#   # bad
#   FOO = 'bar' # spec/foo.rb
#
#   # good
#   FOO = 'bar' # spec/spec_helper.rb
#
#   # good
#   class MyClass # lib/foo/bar.rb
#     FOO = 'bar'
#   end
#
# @example when in a `spec/support/` file
#   # good
#   FOO = 'bar' # spec/support/foo/bar.rb
#
# @example when in a `config/` file
#   # good
#   FOO = 'bar' # config/initializers/foo.rb
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/toplevel_constants.rb:41
class RuboCop::Cop::Gusto::ToplevelConstants < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/toplevel_constants.rb:44
  def on_casgn(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/toplevel_constants.rb:42
RuboCop::Cop::Gusto::ToplevelConstants::MSG = T.let(T.unsafe(nil), String)

# Requires the use of the `paint` gem for terminal color methods on strings
#
# @safety
#   This cop's autocorrection is unsafe because it replaces colorize gem
#   methods with Paint gem methods. If the Paint gem is not included in the
#   project's dependencies, the corrected code will fail at runtime with a
#   NameError (uninitialized constant Paint).
#
# @example
#
#   # bad
#   "string".cyan
#   "string".red
#   "string".green
#   str = "hello"
#   str.cyan
#   "string".colorize(:blue)
#   "string".colorize(:color => :blue)
#   "string".colorize(:color => :blue, :background => :red)
#   "string".blue.on_red
#   "string".colorize(:blue).on_red
#   "string".blue.underline
#
#   # good
#   "string"
#
#   # if color is needed, use `paint` gem
#   Paint["string", :cyan]
#   Paint["string", :red]
#   Paint["string", :green]
#   Paint[str, :cyan]
#   Paint["string", :blue]
#   Paint["string", :blue, :red]
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:40
class RuboCop::Cop::Gusto::UsePaintNotColorize < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:114
  def on_csend(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:105
  def on_send(node); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:219
  def build_paint_call(string_node, foreground, background, styles); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:130
  def colorized_string?(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:136
  def correction(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:199
  def extract_string_and_operations(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:122
  def string_or_colorized_receiver?(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:126
  def string_receiver?(node); end
end

# Common terminal color methods that should be prevented
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:44
RuboCop::Cop::Gusto::UsePaintNotColorize::COLOR_METHODS = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:101
RuboCop::Cop::Gusto::UsePaintNotColorize::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:102
RuboCop::Cop::Gusto::UsePaintNotColorize::PROHIBITED_CLASS = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:103
RuboCop::Cop::Gusto::UsePaintNotColorize::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Set)

# Style modifiers that are applied as additional options in Paint
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/use_paint_not_colorize.rb:90
RuboCop::Cop::Gusto::UsePaintNotColorize::STYLE_MODIFIERS = T.let(T.unsafe(nil), Set)

# Requires VCR to be set to not record in tests.
#
# @example
#   # bad
#   vcr: {record: :all}
#
#   # good
#   vcr: {record: :none}
#
# @see https://github.com/vcr/vcr
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:17
class RuboCop::Cop::Gusto::VcrRecordings < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:27
  def on_pair(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:23
  def vcr_recording?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:43
  def recording_enabled?(option, value); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:39
  def vcr_setting?(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/gusto/vcr_recordings.rb:20
RuboCop::Cop::Gusto::VcrRecordings::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/assignment_first.rb:5
module RuboCop::Cop::InternalAffairs; end

# Check for assignment as the first action in a cop hook.
#
# @example
#   # bad
#   def on_send(node)
#     foo = 1
#     do_something
#   end
#
#   # good
#   def on_send(node)
#     do_something
#     foo = 1
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/assignment_first.rb:21
class RuboCop::Cop::InternalAffairs::AssignmentFirst < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/assignment_first.rb:43
  def on_def(node); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/assignment_first.rb:22
RuboCop::Cop::InternalAffairs::AssignmentFirst::HOOKS = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/assignment_first.rb:41
RuboCop::Cop::InternalAffairs::AssignmentFirst::MSG = T.let(T.unsafe(nil), String)

# Check for missing `RESTRICT_ON_SEND`.
#
# @example
#   # bad
#   class FooCop
#     def on_send(node)
#       # ...
#     end
#   end
#
#   # good
#   class FooCop
#     RESTRICT_ON_SEND = %i[bad_method].freeze
#     def on_send(node)
#       # ...
#     end
#   end
#
# NOTE: This works for us because we do not write cops that investigate every send node.
# Upstream Rubocop chose not to implement this as there are many cops in Core that investigate every node.
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:26
class RuboCop::Cop::InternalAffairs::RequireRestrictOnSend < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:45
  def cop_class_def(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:30
  def defined_send_callback?(param0); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:51
  def on_class(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:39
  def restrict_on_send?(param0); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/internal_affairs/require_restrict_on_send.rb:27
RuboCop::Cop::InternalAffairs::RequireRestrictOnSend::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:7
module RuboCop::Cop::RSpec; end

# Patches the upstream `RSpec/ScatteredLet` cop so that Sorbet `sig`
# declarations attached to `let`/`let!` blocks (Sorbet's RSpec mode)
# do not interrupt the consecutive-let chain.
#
# Without this patch the upstream cop flags valid `sig`+`let`
# arrangements because the intervening `sig` block breaks the
# consecutive-sibling check. (The sig-aware `MoveNode` patch in
# `lib/rubocop/gusto/move_node_patch.rb` handles dragging the `sig`
# along during autocorrect.)
#
# @example
#   # good (no longer flagged)
#   context "..." do
#     sig { returns(Something) }
#     let(:thing) { create(:something) }
#
#     sig { returns(Other) }
#     let(:other) { create(:other) }
#   end
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:27
class RuboCop::Cop::RSpec::ScatteredLet < ::RuboCop::Cop::RSpec::Base
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:32
  def sig_block?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:60
  def build_let_units(children); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:38
  def check_let_declarations(body); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
class RuboCop::Cop::RSpec::ScatteredLet::LetUnit < ::Struct
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def length; end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def length=(_); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def let; end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def let=(_); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def start_index; end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
  def start_index=(_); end

  class << self
    # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
    def [](*_arg0); end

    # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
    def inspect; end

    # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
    def keyword_init?; end

    # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
    def members; end

    # pkg:gem/rubocop-gusto#lib/rubocop/cop/rspec/scattered_let.rb:28
    def new(*_arg0); end
  end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:5
module RuboCop::Cop::Rack; end

# Detects HTTP response headers with uppercase characters.
# HTTP response header keys should be lowercase for compatibility
# with HTTP/2 and modern web standards.
#
# HTTP/2 (RFC 9113) requires all header field names to be lowercase.
# Using lowercase keys ensures compatibility across HTTP versions
# and Rack implementations.
#
# @example
#   # bad
#   headers['Content-Type'] = 'application/json'
#   response.headers['Location'] = '/redirect'
#   response.set_header('X-Custom', 'value')
#   response.headers['Content-Security-Policy'] += policy
#
#   # good
#   headers['content-type'] = 'application/json'
#   response.headers['location'] = '/redirect'
#   response.set_header('x-custom', 'value')
#   response.headers['content-security-policy'] += policy
#
# pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:27
class RuboCop::Cop::Rack::LowercaseHeaderKeys < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:54
  def on_csend(node); end

  # Handle compound assignment: headers['Key'] += val
  # Ruby parses this as an op_asgn node, not a []= send
  #
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:58
  def on_op_asgn(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:47
  def on_send(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:34
  def response_header_method?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:123
  def add_offense_for_header(node, key_value); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:73
  def check_bracket_access(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:83
  def check_header_method(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:88
  def check_key(key_node); end

  # Matches headers receivers that are response-related:
  #   headers (bare method call in controller)
  #   response.headers
  #   self.headers
  # Does NOT match:
  #   conn.headers, request.headers, client.headers, etc.
  #
  # pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:102
  def response_headers_receiver?(receiver); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:30
RuboCop::Cop::Rack::LowercaseHeaderKeys::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/cop/rack/lowercase_header_keys.rb:31
RuboCop::Cop::Rack::LowercaseHeaderKeys::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# RuboCop Gusto project namespace.
#
# pkg:gem/rubocop-gusto#lib/rubocop/gusto/version.rb:4
module RuboCop::Gusto; end

# A plugin that integrates Gusto's standard RuboCop cops and rules.
#
# pkg:gem/rubocop-gusto#lib/rubocop/gusto/plugin.rb:8
class RuboCop::Gusto::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-gusto#lib/rubocop/gusto/version.rb:5
RuboCop::Gusto::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:6
module RuboCop::RSpec; end

# pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:7
module RuboCop::RSpec::Corrector; end

class RuboCop::RSpec::Corrector::MoveNode
  include ::RuboCop::RSpec::Corrector::SigAwareMoveNode
end

# Patches `MoveNode` to treat Sorbet `sig { ... }` blocks as part of the
# `let`/`subject`/hook they precede.
#
# Sorbet's RSpec mode attaches type signatures to memoized helpers via a
# `sig` block immediately above the declaration:
#
#   sig { returns(Something) }
#   let(:thing) { create(:something) }
#
# Several rubocop-rspec cops use `MoveNode` to relocate `let`/`subject`/
# hook nodes (`ScatteredLet`, `LeadingSubject`, `LetBeforeExamples`,
# `HooksBeforeExamples`). Without this patch, the move strands the `sig`
# at the original location. This patch:
#
# 1. Extends the source range of the moved node to include a preceding
#    `sig` block, so `sig` is carried with the move.
# 2. In `move_before`, redirects the insertion point above a preceding
#    `sig` on the destination, so the destination's `sig` pairing stays
#    intact.
#
# pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:27
module RuboCop::RSpec::Corrector::SigAwareMoveNode
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:35
  def move_before(other); end

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:31
  def sig_block?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:42
  def node_range(node); end

  # pkg:gem/rubocop-gusto#lib/rubocop/gusto/move_node_patch.rb:53
  def preceding_sig_block(node); end
end
