inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
plugins:
  - rubocop-gusto

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - vendor/bundle/**/**

Metrics/ParameterLists:
  Enabled: false

# Allow RBS inline type annotation comments (`#:` and `#|`).
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# This rubocop is annoying when we use interfaces a lot
Lint/UnusedMethodArgument:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

# If is sometimes easier to think about than unless sometimes
Style/NegatedIf:
  Enabled: false

# Disabling for now until it's clearer why we want this
Style/FrozenStringLiteralComment:
  Enabled: false

#
# Leaving length metrics to human judgment for now
#
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# This doesn't feel useful
Metrics/CyclomaticComplexity:
  Enabled: false

# This doesn't feel useful
Metrics/PerceivedComplexity:
  Enabled: false

# It's nice to be able to read the condition first before reading the code within the condition
Style/IfUnlessModifier:
  Enabled: false

# This leads to code that is not very readable at times (very long lines)
Style/ConditionalAssignment:
  Enabled: false

# For now, we prefer to lean on clean method signatures as documentation. We may change this later.
Style/Documentation:
  Enabled: false

# This leads to code that is not very readable at times (very long lines)
Layout/FirstArgumentIndentation:
  Enabled: false

# This leads to code that is not very readable at times (very long lines)
Layout/ArgumentAlignment:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/packwerk-extensions.rb

Lint/EmptyClass:
  Exclude:
    - test/**/*
    - tmp/**/*

Lint/EmptyFile:
  Exclude:
    - test/fixtures/minimal/config/environment.rb

Gemspec/DevelopmentDependencies:
  Enabled: false
