name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  minitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          # See comment comes from https://github.com/ruby/setup-ruby#matrix-of-ruby-versions
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - "3.0"
          - 3.1
          - 3.2
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "Minitest tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rake
  static_type_check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Run static type checks
        run: bundle exec srb tc
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Run style checks
        run: bundle exec rubocop
  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [minitest, static_type_check, rubocop]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
      - uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ github.repository }}/${{ github.ref }}: FAILED\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
