name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-workflow-from-shared-config:
    uses: rubyatscale/shared-config/.github/workflows/ci.yml@jms/test_command_input
    secrets: inherit
    with:
      test-command: "bundle exec rake"
